Modernizing toolchains

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -157,7 +157,7 @@ jobs:
     steps:
       - name: Faile when Corresponding Build wouldn't succeeded
         if: ${{needs.build.result != 'success' }}
-        run: echo "BUILD FAILED" >&2; xit 1
+        run: echo "BUILD FAILED" >&2; exit 1
       - uses: actions/checkout@v3
         with:
           ref: ${{github.event.pull_request.head.sha || github.sha}}
